return 
[ [ One(Q), One(Q), One(Q), One(Q), 
      One(Q), One(Q) ], 
  [ One(Q), One(Q), One(Q), One(Q), f1, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), One(Q), f2, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), One(Q), f3, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), One(Q), f4, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), One(Q), f1*f2, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), One(Q), f1*f3, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), One(Q), f2*f3, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), One(Q), f2*f4, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), One(Q), f3*f4, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), One(Q), 
      f1*f2*f3, One(Q) ], 
  [ One(Q), One(Q), One(Q), One(Q), 
      f1*f3*f4, One(Q) ], 
  [ One(Q), One(Q), One(Q), One(Q), 
      f2*f3*f4, One(Q) ], 
  [ One(Q), One(Q), One(Q), One(Q), 
      f1*f2*f3*f4, One(Q) ], 
  [ One(Q), One(Q), f1, f2, One(Q), One(Q) ]
    , [ One(Q), One(Q), f1, f3, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), f1, f4, One(Q), One(Q) ]
    , [ One(Q), One(Q), f1, f2*f3, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), f1, f2*f4, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), f1, f3*f4, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), f1, f2*f3*f4, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), f2, f3, One(Q), One(Q) ]
    , [ One(Q), One(Q), f2, f4, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), f2, f1*f3, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), f2, f3*f4, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), f2, f1*f3*f4, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), f3, f4, One(Q), One(Q) ]
    , [ One(Q), One(Q), f3, f1*f2, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), f3, f2*f4, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), f3, f1*f2*f3, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), f4, f2*f3, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), f1*f2, f1*f3, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), f1*f2, f1*f4, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), f1*f2, f3*f4, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), f1*f2, f1*f3*f4, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), f2*f3, f2*f4, One(Q), 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), f1, f2, One(Q) ]
    , [ One(Q), One(Q), One(Q), f1, f3, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), f1, f2*f3, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), f1, f3*f4, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), f1, f2*f3*f4, 
      One(Q) ], 
  [ One(Q), One(Q), f2, f3, f1, One(Q) ], 
  [ One(Q), One(Q), f2, f1*f3, f1, One(Q) ], 
  [ One(Q), One(Q), f2, f3*f4, f1, One(Q) ], 
  [ One(Q), One(Q), f2, f1*f3*f4, f1, One(Q) ], 
  [ One(Q), One(Q), f1, f3*f4, f3, One(Q) ], 
  [ One(Q), One(Q), f3, f1*f2, f1, One(Q) ], 
  [ One(Q), One(Q), f3, f2*f4, f1, One(Q) ], 
  [ One(Q), One(Q), f3, f1*f2*f3, f1, One(Q) ], 
  [ One(Q), One(Q), f1*f2, f1*f3, f1, One(Q) ], 
  [ One(Q), One(Q), f1*f2, f1*f4, f1, One(Q) ], 
  [ One(Q), One(Q), f1*f2, f3*f4, f1, One(Q) ], 
  [ One(Q), One(Q), f1*f2, f1*f3*f4, f1, One(Q) ], 
  [ One(Q), One(Q), f1, f3*f4, f2*f3, One(Q) ], 
  [ One(Q), One(Q), One(Q), f2, f3, One(Q) ]
    , [ One(Q), One(Q), One(Q), f2, f4, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), f2, f1*f3, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), f2, f3*f4, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), f2, f1*f3*f4, 
      One(Q) ], 
  [ One(Q), One(Q), f1, f3, f2, One(Q) ], 
  [ One(Q), One(Q), f1, f4, f2, One(Q) ], 
  [ One(Q), One(Q), f1, f2*f3, f2, One(Q) ], 
  [ One(Q), One(Q), f1, f2*f4, f2, One(Q) ], 
  [ One(Q), One(Q), f1, f3*f4, f2, One(Q) ], 
  [ One(Q), One(Q), f1, f2*f3*f4, f2, One(Q) ], 
  [ One(Q), One(Q), f3, f4, f2, One(Q) ], 
  [ One(Q), One(Q), f3, f2*f4, f2, One(Q) ], 
  [ One(Q), One(Q), f4, f2*f3, f2, One(Q) ], 
  [ One(Q), One(Q), f2*f3, f2*f4, f2, One(Q) ], 
  [ One(Q), One(Q), One(Q), f3, f4, One(Q) ]
    , [ One(Q), One(Q), One(Q), f3, f1*f2, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), f3, f2*f4, 
      One(Q) ], 
  [ One(Q), One(Q), f1, f2, f3, One(Q) ], 
  [ One(Q), One(Q), f1, f2*f3*f4, f3, One(Q) ], 
  [ One(Q), One(Q), f2, f4, f3, One(Q) ], 
  [ One(Q), One(Q), f2, f3*f4, f3, One(Q) ], 
  [ One(Q), One(Q), f3, f4, f1*f2, One(Q) ], 
  [ One(Q), One(Q), One(Q), f4, f2*f3, 
      One(Q) ], 
  [ One(Q), One(Q), f2, f3, f4, One(Q) ], 
  [ One(Q), One(Q), One(Q), f1*f2, f1*f3, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), f1*f2, f3*f4, 
      One(Q) ], 
  [ One(Q), One(Q), One(Q), f1*f2, f1*f3*f4, 
      One(Q) ], 
  [ One(Q), One(Q), f1*f2, f3*f4, f1*f3, One(Q) ], 
  [ One(Q), One(Q), One(Q), f2*f3, f2*f4, 
      One(Q) ], 
  [ One(Q), One(Q), f1, f2, f3*f4, One(Q) ], 
  [ f1, f2, f3, f2*f4, One(Q), One(Q) ], 
  [ One(Q), f1, One(Q), f2, f3, One(Q) ], 
  [ One(Q), f1, One(Q), f2, f3*f4, One(Q) ], 
  [ One(Q), f1, f3, f4, f2, One(Q) ], 
  [ One(Q), f2, One(Q), f3, f4, One(Q) ] ]
;
